version: '3'

services :

  miwamp:
    build: ./wamp-php-app
    image: myphpapp-win:latest
    ports:
      - "8000:80"

  mientorno:
    depends_on:
      - miwamp
    build: ./mi-entorno
    image: mientorno-win:latest
    volumes:
      - C:/miEntorno/Git:C:/miEntorno/Git
      - C:/miEntorno/apache-maven-repository:C:/miEntorno/apache-maven-repository
     
